services:
  chalet-app:
    #build: .
    image: ghcr.io/noudbeer/chalet-bozel/chalet-bozel-app-test:latest
    container_name: chalet-bozel-app
    ports:
      - "3001:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: always